#!/usr/bin/env python3
"""package-site.py — build a production copy of the site in dist/ (and optionally a zip of it).

    python3 tools/package-site.py --site-url https://example.com --pretty --zip

What it does
  * copies only the files the site serves (no tools/, .github/, content sources or tests)
  * writes site/config.js with the public URL and clean-URL mode
  * generates sitemap.xml (every page, every entity) and robots.txt with an absolute sitemap link
  * makes the social-preview image and canonical links absolute
  * rewrites root-relative paths in 404.html, manifest.webmanifest and .htaccess when the site
    lives under a sub-path (--base-path /atlas/)
  * optionally zips dist/ so the archive can be uploaded and extracted in one step

The output is plain files: upload dist/ (or extract the zip) into the web root of any static host.
"""
import argparse, datetime, json, os, re, shutil, subprocess, sys, zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXCLUDE_DIRS = ("tools/", ".github/", "content/")
KEEP_IN_CONTENT = ("content/roadmap.json",)
EXCLUDE_FILES = (".gitignore", "vercel.json", "_headers", "tools/qa/shots")
SECTIONS = {"physiology": "topic.html", "symptoms": "symptom.html", "conditions": "condition.html", "tests": "test.html", "imaging": "study.html",
            "procedures": "procedure.html", "medications": "medication.html", "first-aid": "topic.html", "health": "topic.html"}

def served_files():
    out = subprocess.check_output(["git", "ls-files", "--cached", "--others", "--exclude-standard"], cwd=ROOT, text=True)
    files = []
    for rel in out.splitlines():
        if not rel or not os.path.isfile(os.path.join(ROOT, rel)): continue
        if rel in EXCLUDE_FILES or rel.endswith(".glb.json"): continue
        if rel.startswith(EXCLUDE_DIRS) and rel not in KEEP_IN_CONTENT: continue
        files.append(rel)
    return files

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--site-url", default="", help="public origin, e.g. https://example.com (used for canonical links, sitemap, social image)")
    ap.add_argument("--base-path", default="/", help="path under the origin where the site lives, e.g. /atlas/ (default /)")
    ap.add_argument("--pretty", action="store_true", help="enable clean URLs (/conditions/gout); requires the .htaccess rewrites or equivalent")
    ap.add_argument("--out", default=os.path.join(ROOT, "dist"))
    ap.add_argument("--zip", action="store_true", help="also write <out>/human-body-site.zip")
    ap.add_argument("--redirect-host", action="append", default=[], help="old host name to redirect permanently to --site-url (repeatable), e.g. medical.mjunaid.net")
    a = ap.parse_args()
    site = a.site_url.rstrip("/")
    base = "/" + a.base_path.strip("/") + "/" if a.base_path.strip("/") else "/"
    origin = site + base if site else base

    out = os.path.abspath(a.out)
    if os.path.exists(out): shutil.rmtree(out)
    files = served_files()
    for rel in files:
        dst = os.path.join(out, rel); os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copy2(os.path.join(ROOT, rel), dst)

    # ---- server-side pull script (used by the Hostinger cron job; lives in the deploy branch so the server can fetch it)
    shutil.copy2(os.path.join(ROOT, "tools", "hostinger-pull.sh"), os.path.join(out, "hostinger-pull.sh"))

    # ---- version stamp: release from VERSION, build id from git
    version = open(os.path.join(ROOT, "VERSION"), encoding="utf-8").read().strip()
    try: build = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip()
    except Exception: build = ""
    with open(os.path.join(out, "site", "version.js"), "w", encoding="utf-8") as f:
        f.write(f"// generated by tools/package-site.py\nexport const VERSION = {json.dumps(version)};\nexport const BUILD = {json.dumps(build)};\n")

    # ---- runtime configuration
    with open(os.path.join(out, "site", "config.js"), "w", encoding="utf-8") as f:
        f.write("// generated by tools/package-site.py\nexport const CONFIG = " + json.dumps({"siteUrl": site + base.rstrip("/") if site else "", "prettyUrls": bool(a.pretty)}, indent=2) + ";\n")

    # ---- sitemap
    know = json.load(open(os.path.join(ROOT, "data", "content", "clinical.json"), encoding="utf-8"))
    atlas = json.load(open(os.path.join(ROOT, "data", "hd", "atlas.json"), encoding="utf-8"))
    content = json.load(open(os.path.join(ROOT, "data", "content", "atlas-content.json"), encoding="utf-8"))
    today = datetime.date.today().isoformat()
    urls = [("", "1.0", "weekly"), ("explorer/", "0.9", "monthly"), ("systems/", "0.8", "monthly"), ("organs/", "0.8", "monthly"), ("learn/terminology.html", "0.7", "monthly"), ("study/", "0.6", "monthly"), ("roadmap/", "0.3", "monthly")]
    for d in SECTIONS: urls.append((f"{d}/", "0.8", "weekly"))
    def detail(d, page, i): return f"{d}/{i}" if a.pretty else f"{d}/{page}?id={i}"
    for s in atlas["systems"]: urls.append((detail("systems", "system.html", s["id"]), "0.6", "monthly"))
    for o in content["organs"]: urls.append((detail("organs", "organ.html", o["id"]), "0.6", "monthly"))
    for kind, names in know["names"].items():
        for i in names: urls.append((detail(kind, SECTIONS[kind], i), "0.7", "monthly"))
    esc = lambda s: s.replace("&", "&amp;")
    xml = ['<?xml version="1.0" encoding="UTF-8"?>', '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for path, prio, freq in urls:
        xml.append(f"  <url><loc>{esc(origin + path)}</loc><lastmod>{today}</lastmod><changefreq>{freq}</changefreq><priority>{prio}</priority></url>")
    xml.append("</urlset>")
    open(os.path.join(out, "sitemap.xml"), "w", encoding="utf-8").write("\n".join(xml) + "\n")
    open(os.path.join(out, "robots.txt"), "w", encoding="utf-8").write(f"User-agent: *\nAllow: {base}\nDisallow: {base}search/\nSitemap: {origin}sitemap.xml\n")

    # ---- absolute social image and canonical home link
    p = os.path.join(out, "index.html"); s = open(p, encoding="utf-8").read()
    s = s.replace('content="site/og-cover.png"', f'content="{origin}site/og-cover.png"')
    s = s.replace('<link rel="canonical" href="index.html">', f'<link rel="canonical" href="{origin}">')
    open(p, "w", encoding="utf-8").write(s)

    # ---- permanent redirects from retired host names to the canonical site
    if a.redirect_host and site:
        p = os.path.join(out, ".htaccess"); s = open(p, encoding="utf-8").read()
        rules = "".join(f"  RewriteCond %{{HTTP_HOST}} ^{re.escape(h)}$ [NC]\n  RewriteRule ^ {site}%{{REQUEST_URI}} [L,R=301]\n" for h in a.redirect_host)
        s = s.replace("  # ---- clean URLs", "  # ---- retired host names redirect to the canonical site\n" + rules + "\n  # ---- clean URLs", 1)
        open(p, "w", encoding="utf-8").write(s)

    # ---- sub-path installs: root-relative references
    if base != "/":
        for rel in ("404.html", "manifest.webmanifest", ".htaccess"):
            p = os.path.join(out, rel)
            if not os.path.exists(p): continue
            s = open(p, encoding="utf-8").read()
            s = re.sub(r'(href|src|content|action)="/(?!/)', lambda m: f'{m.group(1)}="{base}', s)
            s = s.replace('"src": "/', f'"src": "{base}').replace('"start_url": "/', f'"start_url": "{base}')
            s = s.replace("ErrorDocument 404 /404.html", f"ErrorDocument 404 {base}404.html")
            open(p, "w", encoding="utf-8").write(s)

    n = sum(len(fs) for _, _, fs in os.walk(out)); size = sum(os.path.getsize(os.path.join(r, f)) for r, _, fs in os.walk(out) for f in fs)
    print(f"dist: {n} files, {size / 1048576:.1f} MB, {len(urls)} sitemap URLs, version {version} build {build[:7]}, siteUrl={site or '(relative)'} base={base} prettyUrls={bool(a.pretty)}")
    if a.zip:
        zp = os.path.join(out, "human-body-site.zip")
        with zipfile.ZipFile(zp, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as z:
            for r, _, fs in os.walk(out):
                for f in fs:
                    full = os.path.join(r, f)
                    if full == zp: continue
                    z.write(full, os.path.relpath(full, out))
        print(f"zip: {zp} ({os.path.getsize(zp) / 1048576:.1f} MB)")

if __name__ == "__main__":
    main()
